config/routes.rb
Apizoo::Application.routes.draw do
  resources :habitats

  resources :species

  resources :animals

  root :to => 'species#index'

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  attr_accessible :name, :description, :species_id, :habitat_id, :photo_file_name, :photo_content_type, :photo_file_size, :photo_updated_at
  belongs_to :species
  belongs_to :habitat
end

app/models/habitat.rb
class Habitat < ActiveRecord::Base
  attr_accessible :name, :description, :photo_file_name, :photo_content_type, :photo_file_size, :photo_updated_at
  has_many :animals
end

app/models/species.rb
class Species < ActiveRecord::Base
  attr_accessible :name, :description, :photo, :photo_file_name, :photo_content_type, :photo_file_size, :photo_updated_at
  has_many :animals
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
    respond_to do |format|
      format.html
      format.json { render :json => @animals}    
    end
  end

  def show
    @animal = Animal.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @animal}    
    end
  end

  def new
    @animal = Animal.new
  end

  def create
    @species = Species.find(params[:animal][:species_id])
    @animal = @species.animals.build(params[:animal])
    if @animal.save
      redirect_to @animal, :notice => "Successfully created animal."
    else
      render :action => 'new'
    end
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update_attributes(params[:animal])
      redirect_to @animal, :notice  => "Successfully updated animal."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_url, :notice => "Successfully destroyed animal."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/habitats_controller.rb
class HabitatsController < ApplicationController
  def index
    @habitats = Habitat.all
  end

  def show
    @habitat = Habitat.find(params[:id])
  end

  def new
    @habitat = Habitat.new
  end

  def create
    @habitat = Habitat.new(params[:habitat])
    if @habitat.save
      redirect_to @habitat, :notice => "Successfully created habitat."
    else
      render :action => 'new'
    end
  end

  def edit
    @habitat = Habitat.find(params[:id])
  end

  def update
    @habitat = Habitat.find(params[:id])
    if @habitat.update_attributes(params[:habitat])
      redirect_to @habitat, :notice  => "Successfully updated habitat."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @habitat = Habitat.find(params[:id])
    @habitat.destroy
    redirect_to habitats_url, :notice => "Successfully destroyed habitat."
  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def index
    @species = Species.all
  end

  def show
    @species = Species.find(params[:id])
  end

  def new
    @species = Species.new
  end

  def create
    @species = Species.new(params[:species])
    if @species.save
      redirect_to @species, :notice => "Successfully created species."
    else
      render :action => 'new'
    end
  end

  def edit
    @species = Species.find(params[:id])
  end

  def update
    @species = Species.find(params[:id])
    if @species.update_attributes(params[:species])
      redirect_to @species, :notice  => "Successfully updated species."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @species = Species.find(params[:id])
    @species.destroy
    redirect_to species_index_url, :notice => "Successfully destroyed species."
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/habitats_helper.rb
module HabitatsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/animals/_form.html.haml
= form_for @animal do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.label :description
    %br
    = f.text_area :description
  %p
    = select('animal', 'species_id', Species.all.collect {|s| [ s.name, s.id ] })
  %p
    = select('animal', 'habitat_id', Habitat.all.collect {|h| [ h.name, h.id ] })
  %p
    = f.label :photo_file_name
    %br
    = f.text_field :photo_file_name
  %p
    = f.label :photo_content_type
    %br
    = f.text_field :photo_content_type
  %p
    = f.label :photo_file_size
    %br
    = f.text_field :photo_file_size
  %p
    = f.label :photo_updated_at
    %br
    = f.text_field :photo_updated_at
  %p
    = f.submit

app/views/animals/edit.html.haml
- title "Edit Animal"

= render 'form'

%p
  = link_to "Show", @animal
  |
  = link_to "View All", animals_path

app/views/animals/index.html.haml
- title "Animals"

%table
  %tr
    %th Name
    %th Description
    %th Species
    %th Habitat
    %th Photo file name
    %th Photo content type
    %th Photo file size
    %th Photo updated at
  - for animal in @animals
    %tr
      %td= animal.name
      %td= animal.description
      %td= animal.species.name unless animal.species.nil?
      %td= animal.habitat.name unless animal.habitat.nil?
      %td= animal.photo_file_name
      %td= animal.photo_content_type
      %td= animal.photo_file_size
      %td= animal.photo_updated_at
      %td= link_to 'Show', animal
      %td= link_to 'Edit', edit_animal_path(animal)
      %td= link_to 'Destroy', animal, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Animal", new_animal_path

app/views/animals/new.html.haml
- title "New Animal"

= render 'form'

%p= link_to "Back to List", animals_path

app/views/animals/show.html.haml
- title "Animal"

%p
  %strong Name:
  = @animal.name
%p
  %strong Description:
  = @animal.description
%p
  %strong Species:
  = @animal.species.name unless @animal.species.nil?
%p
  %strong Habitat:
  = @animal.habitat.name unless @animal.habitat.nil?
%p
  %strong Photo File Name:
  = @animal.photo_file_name
%p
  %strong Photo Content Type:
  = @animal.photo_content_type
%p
  %strong Photo File Size:
  = @animal.photo_file_size
%p
  %strong Photo Updated At:
  = @animal.photo_updated_at

%p
  = link_to "Edit", edit_animal_path(@animal)
  |
  = link_to "Destroy", @animal, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", animals_path

app/views/habitats/_form.html.haml
= form_for @habitat do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.label :description
    %br
    = f.text_area :description
  %p
    = f.label :photo_file_name
    %br
    = f.text_field :photo_file_name
  %p
    = f.label :photo_content_type
    %br
    = f.text_field :photo_content_type
  %p
    = f.label :photo_file_size
    %br
    = f.text_field :photo_file_size
  %p
    = f.label :photo_updated_at
    %br
    = f.text_field :photo_updated_at
  %p
    = f.submit

app/views/habitats/edit.html.haml
- title "Edit Habitat"

= render 'form'

%p
  = link_to "Show", @habitat
  |
  = link_to "View All", habitats_path

app/views/habitats/index.html.haml
- title "Habitats"

%table
  %tr
    %th Name
    %th Description
    %th Photo file name
    %th Photo content type
    %th Photo file size
    %th Photo updated at
  - for habitat in @habitats
    %tr
      %td= habitat.name
      %td= habitat.description
      %td= habitat.photo_file_name
      %td= habitat.photo_content_type
      %td= habitat.photo_file_size
      %td= habitat.photo_updated_at
      %td= link_to 'Show', habitat
      %td= link_to 'Edit', edit_habitat_path(habitat)
      %td= link_to 'Destroy', habitat, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Habitat", new_habitat_path

app/views/habitats/new.html.haml
- title "New Habitat"

= render 'form'

%p= link_to "Back to List", habitats_path

app/views/habitats/show.html.haml
- title "Habitat"

%p
  %strong Name:
  = @habitat.name
%p
  %strong Description:
  = @habitat.description
%p
  %strong Photo File Name:
  = @habitat.photo_file_name
%p
  %strong Photo Content Type:
  = @habitat.photo_content_type
%p
  %strong Photo File Size:
  = @habitat.photo_file_size
%p
  %strong Photo Updated At:
  = @habitat.photo_updated_at

%p
  = link_to "Edit", edit_habitat_path(@habitat)
  |
  = link_to "Destroy", @habitat, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", habitats_path

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield

app/views/species/_form.html.haml
= form_for @species, :html => { :multipart => true } do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.label :description
    %br
    = f.text_area :description
  %p
    = image_tag @species.photo.url(:medium) if @species.photo.exists?
  %p
    = f.file_field :photo
  %p
    = f.submit

app/views/species/edit.html.haml
- title "Edit Species"

= render 'form'

%p
  = link_to "Show", @species
  |
  = link_to "View All", species_path

app/views/species/index.html.haml
- title "Species"

%table
  %tr
    %th Name
    %th Description
    %th Photo file name
    %th Photo content type
    %th Photo file size
    %th Photo updated at
  - for species in @species
    %tr
      %td= species.name
      %td= species.description
      %td= species.photo_file_name
      %td= species.photo_content_type
      %td= species.photo_file_size
      %td= species.photo_updated_at
      %td= link_to 'Show', species
      %td= link_to 'Edit', edit_species_path(species)
      %td= link_to 'Destroy', species, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Species", new_species_path

app/views/species/new.html.haml
- title "New Species"

= render 'form'

app/views/species/show.html.haml
- title "Species"

%p
  %strong Name:
  = @species.name
%p
  %strong Description:
  = @species.description
%p
  = image_tag @species.photo.url(:thumb)
%p
  = link_to "Edit", edit_species_path(@species)
  |
  = link_to "Destroy", @species, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", species_index_path